title: "Tutormu"
email: 
timezone: UTC
baseurl: "/"
permalink: "/:title/"
logo: 'assets/images/credits.png'
favicon: 'assets/images/icon.png'
author: Fauzan
paginate: 30
disqus: ''
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: 

# Authors
authors:
  fauzan:
    name: Fauzan
    display_name: Fauzan
    avatar: 'assets/images/fauzan.png'
    email: 
    web: https://tutormu.com
    twitter: 
    description: "Penikmat kopi. Penyuka angka dan logika. Sedang membangun Tutormu.com sebagai tempat berbagi ilmu dan pengalaman belajar."
  john:
    name: John
    display_name: John
    avatar: 'assets/images/john.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  instagram: https://www.instagram.com/tutormucom/
  youtube: https://www.youtube.com/@tutormu
  tiktok: https://www.tiktok.com/@tutormu
# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
